export enum PaymentIntegrationType {
  PAYMENT = "PAYMENT",
  TRANSFER = "TRANSFER",
  TOPUP = "TOPUP",
  INTERNAL_TRANSFER = "INTERNAL_TRANSFER",
  NONE = "NONE",
}

export enum PaymentCategory {
  WALLET_TRANSFER = "Wallet Transfer",
  BILL_PAYMENT = "Bill Payment",
  TICKET_PAYMENT = "Ticket Payment",
  SUBSCRIPTION_PAYMENT = "Subscription Payment",
  FUNDRAISER_DONATION = "Fundraiser/Donation",
  TOP_UP = "Top-Up (Airtime & Data Recharge)",
  MERCHANT_PAYMENT = "Merchant Payment",
  BANK_TRANSFER = "Bank Transfer",
  GOVERNMENT_PAYMENT = "Government Payments",
  E_COMMERCE_PAYMENT = "E-commerce Payment",
  P2P_PAYMENT = "Peer-to-Peer (P2P) Payments",
  CREDIT_DEBIT_CARD_PAYMENT = "Credit/Debit Card Payments",
  OTHER = "other",
}

export enum TransactionAmountType {
  PREDEFINED = "PREDEFINED",
  USER_DEFINED = "USER_DEFINED",
  NONE = "NONE",
}

export enum Visibility {
  EVERYONE = "EVERYONE",
  FOR_STUFF = "FOR_STUFF",
  VIP_CUSTOMERS = "VIP_CUSTOMERS",
  FOR_TESTERS = "FOR_TESTERS",
  NONE = "NONE",
}

export enum PaymentOperationType {
  ENQUIRY = "ENQUIRY",
  PROCESS_PAYMENT_AND_NOTIFY_WEBHOOK = "PROCESS_PAYMENT_AND_NOTIFY_WEBHOOK",
  NONE = "NONE",
}

export enum FormType {
  INIT = "INIT",
  INDEX = "INDEX",
  REMARK = "REMARK",
  ENQUIRY = "ENQUIRY",
  PAYMENT = "PAYMENT",
  NONE = "NONE",
}

export enum DataType {
  STRING = "STRING",
  INT = "INT",
  LONG = "LONG",
  DOUBLE = "DOUBLE",
  BOOLEAN = "BOOLEAN",
  DATETIME = "DATETIME",
  NUMBER = "NUMBER",
  DATE = "DATE",
  COLLECTION = "COLLECTION",
  NONE = "NONE",
}

export enum InputType {
  HEADER = "HEADER",
  BODY = "BODY",
  QUERY = "QUERY",
  PATH = "PATH",
  NONE = "NONE",
}

export enum TransferMapping {
  AMOUNT = "AMOUNT",
  CREDIT_ACCOUNT = "CREDIT_ACCOUNT",
  REASON = "REASON",
  NONE = "NONE",
}

export enum AuthType {
  NONE = "NONE",
  BASIC = "BASIC",
  BEARER = "BEARER",
  API_KEY = "API_KEY",
  JWT = "JWT",
  OAUTH1 = "OAUTH1",
  OAUTH2 = "OAUTH2",
  PKCE = "PKCE",
  SESSION_COOKIE = "SESSION_COOKIE",
  DEVICE_AUTHORIZATION_FLOW = "DEVICE_AUTHORIZATION_FLOW",
  OPENID_CONNECT = "OPENID_CONNECT",
  HMAC = "HMAC",
  AWS_SIGV4 = "AWS_SIGV4",
  DIGEST = "DIGEST",
  CLIENT_CERTIFICATE = "CLIENT_CERTIFICATE",
  SAML = "SAML",
  LDAP = "LDAP",
  KERBEROS = "KERBEROS",
  GOOGLE_SERVICE_ACCOUNT = "GOOGLE_SERVICE_ACCOUNT",
  AZURE_SAS_TOKEN = "AZURE_SAS_TOKEN",
  CUSTOM_HEADER = "CUSTOM_HEADER",
  TOKEN_EXCHANGE = "TOKEN_EXCHANGE",
  CUSTOM_OAUTH = "CUSTOM_OAUTH",
  OTHER = "OTHER",
}

export enum Auth {
  NONE = "NONE",
  BASIC = "BASIC",
  BEARER = "BEARER",
  API_KEY = "API_KEY",
  JWT = "JWT",
  OAUTH1 = "OAUTH1",
  OAUTH2 = "OAUTH2",
  PKCE = "PKCE",
  DEVICE_AUTHORIZATION_FLOW = "DEVICE_AUTHORIZATION_FLOW",
  OPENID_CONNECT = "OPENID_CONNECT",
  HMAC = "HMAC",
  AWS_SIGV4 = "AWS_SIGV4",
  DIGEST = "DIGEST",
  CLIENT_CERTIFICATE = "CLIENT_CERTIFICATE",
  SAML = "SAML",
  LDAP = "LDAP",
  KERBEROS = "KERBEROS",
  SESSION_COOKIE = "SESSION_COOKIE",
  GOOGLE_SERVICE_ACCOUNT = "GOOGLE_SERVICE_ACCOUNT",
  AZURE_SAS_TOKEN = "AZURE_SAS_TOKEN",
  CUSTOM_HEADER = "CUSTOM_HEADER",
  TOKEN_EXCHANGE = "TOKEN_EXCHANGE",
  CUSTOM_OAUTH = "CUSTOM_OAUTH",
  OTHER = "OTHER",
}

export enum Protocol {
  HTTP = "HTTP",
  HTTPS = "HTTPS",
}

export enum IntegrationType {
  JSON = "JSON",
  SOAP = "SOAP",
  XML = "XML",
  NONE = "NONE",
}

export enum MappingPathPrefix {
  ENQUIRY_FORM_INPUT_PREFIX = "$enquiryFormInput.",
  ENQUIRY_API_RESPONSE_PREFIX = "$enquiryApiResponse.",
  PAYMENT_FORM_INPUT_PREFIX = "$paymentFormInput.",
  NOTIFY_API_RESPONSE_PREFIX = "$notifyApiResponse.",
  CURRENT_CUSTOMER_PREFIX = "$currentCustomer.",
  DEBITED_ACCOUNT_PREFIX = "$debitedAccount.",
  CREDITED_ACCOUNT_PREFIX = "$creditedAccount.",
  TRANSACTION_PREFIX = "$transaction.",
}

export enum MenuLayoutType {
  GRID = "GRID",
  LIST = "LIST",
}

export enum PaginationType {
  PAGINATED = "PAGINATED",
  INFINITE_SCROLL = "INFINITE_SCROLL",
  NONE = "NONE",
}

export enum BodyType {
  NONE = "NONE",
  APPLICATION_JSON = "APPLICATION/JSON",
  APPLICATION_XML = "APPLICATION/XML",
  APPLICATION_OCTET_STREAM = "APPLICATION/OCTET-STREAM",
  APPLICATION_GRAPHQL = "APPLICATION/GRAPHQL",
  APPLICATION_LD_JSON = "APPLICATION/LD+JSON",
  APPLICATION_X_CUSTOM = "APPLICATION/X-CUSTOM",
  TEXT_PLAIN = "TEXT/PLAIN",
  TEXT_HTML = "TEXT/HTML",
  TEXT_CSS = "TEXT/CSS",
  APPLICATION_JAVASCRIPT = "APPLICATION/JAVASCRIPT",
  TEXT_MARKDOWN = "TEXT/MARKDOWN",
  TEXT_CSV = "TEXT/CSV",
  TEXT_XML = "TEXT/XML",
  APPLICATION_PDF = "APPLICATION/PDF",
  APPLICATION_ZIP = "APPLICATION/ZIP",
  APPLICATION_X_WWW_FORM_URLENCODED = "APPLICATION/X-WWW-FORM-URLENCODED",
  MULTIPART_FORM_DATA = "MULTIPART/FORM-DATA",
  MULTIPART_MIXED = "MULTIPART/MIXED",
  MULTIPART_ALTERNATIVE = "MULTIPART/ALTERNATIVE",
  TEXT_RTF = "TEXT/RTF",
  TEXT_VCARD = "TEXT/VCARD",
  APPLICATION_VND_MS_EXCEL = "APPLICATION/VND.MS-EXCEL",
  APPLICATION_MSWORD = "APPLICATION/MSWORD",
  APPLICATION_VND_MS_POWERPOINT = "APPLICATION/VND.MS-POWERPOINT",
  APPLICATION_ATOM_XML = "APPLICATION/ATOM+XML",
  APPLICATION_RSS_XML = "APPLICATION/RSS+XML",
  APPLICATION_VND_API_JSON = "APPLICATION/VND.API+JSON",
  APPLICATION_CBOR = "APPLICATION/CBOR",
  APPLICATION_VND_GOOGLE_EARTH_KML_XML = "APPLICATION/VND.GOOGLE-EARTH.KML+XML",
  APPLICATION_X_SH = "APPLICATION/X-SH",
  APPLICATION_X_HTTPD_PHP = "APPLICATION/X-HTTPD-PHP",
  APPLICATION_GZIP = "APPLICATION/GZIP",
  APPLICATION_X_TAR = "APPLICATION/X-TAR",
  APPLICATION_X_7Z_COMPRESSED = "APPLICATION/X-7Z-COMPRESSED",
  APPLICATION_X_SHOCKWAVE_FLASH = "APPLICATION/X-SHOCKWAVE-FLASH",
  APPLICATION_VND_MAPBOX_VECTOR_TILE = "APPLICATION/VND.MAPBOX-VECTOR-TILE",
  IMAGE_JPEG = "IMAGE/JPEG",
  IMAGE_PNG = "IMAGE/PNG",
  IMAGE_GIF = "IMAGE/GIF",
  IMAGE_SVG_XML = "IMAGE/SVG+XML",
  IMAGE_WEBP = "IMAGE/WEBP",
  IMAGE_BMP = "IMAGE/BMP",
  IMAGE_TIFF = "IMAGE/TIFF",
  IMAGE_VND_MICROSOFT_ICON = "IMAGE/VND.MICROSOFT.ICON",
  AUDIO_MPEG = "AUDIO/MPEG",
  AUDIO_OGG = "AUDIO/OGG",
  AUDIO_WAV = "AUDIO/WAV",
  AUDIO_FLAC = "AUDIO/FLAC",
  AUDIO_AAC = "AUDIO/AAC",
  AUDIO_WEBM = "AUDIO/WEBM",
  VIDEO_MP4 = "VIDEO/MP4",
  VIDEO_OGG = "VIDEO/OGG",
  VIDEO_WEBM = "VIDEO/WEBM",
  VIDEO_X_MSVIDEO = "VIDEO/X-MSVIDEO",
  VIDEO_X_FLV = "VIDEO/X-FLV",
  VIDEO_MPEG = "VIDEO/MPEG",
  FONT_WOFF = "FONT/WOFF",
  FONT_WOFF2 = "FONT/WOFF2",
  FONT_TTF = "FONT/TTF",
  FONT_OTF = "FONT/OTF",
}

export enum HttpMethod {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  PATCH = "PATCH",
  OPTIONS = "OPTIONS",
  NONE = "NONE",
}

export enum LogicalOperators {
  AND = "AND",
  OR = "OR",
  NONE = "NONE",
}

export enum Operators {
  EQ = "EQ",
  NEQ = "NEQ",
  LT = "LT",
  LTE = "LTE",
  GT = "GT",
  GTE = "GTE",
  IN = "IN",
  NIN = "NIN",
  NNULL = "NNULL",
  PATTERN = "PATTERN",
  MAX_LENGTH = "MAX_LENGTH",
  MIN_LENGTH = "MIN_LENGTH",
  CONTAINS = "CONTAINS",
  NCONTAINS = "NCONTAINS",
  ICONTAINS = "ICONTAINS",
  STARTS_WITH = "STARTS_WITH",
  NSTARTS_WITH = "NSTARTS_WITH",
  ISTARTS_WITH = "ISTARTS_WITH",
  NISTARTS_WITH = "NISTARTS_WITH",
  ENDS_WITH = "ENDS_WITH",
  NENDS_WITH = "NENDS_WITH",
  IENDS_WITH = "IENDS_WITH",
  NIENDS_WITH = "NIENDS_WITH",
  BETWEEN = "BETWEEN",
  NBETWEEN = "NBETWEEN",
  EMPTY = "EMPTY",
  NEMPTY = "NEMPTY",
}

export enum RetryStrategy {
  FIXED_DELAY = "FIXED_DELAY",
  EXPONENTIAL_BACKOFF = "EXPONENTIAL_BACKOFF",
  NONE = "NONE",
}

export enum GenerationType {
  SEQUENTIAL = "SEQUENTIAL",
  RANDOM = "RANDOM",
  PATTERN_BASED = "PATTERN_BASED",
  UUID = "UUID",
  DATE = "DATE",
  DATE_TIME = "DATE_TIME",
  NONE = "NONE",
}

export enum DateStepUnit {
  DAYS = "DAYS",
  HOURS = "HOURS",
  MINUTES = "MINUTES",
  SECONDS = "SECONDS",
}

export enum InterfaceType {
  INPUT = "INPUT",
  INPUT_PHONE = "INPUT_PHONE",
  INPUT_MONEY = "INPUT_MONEY",
  INPUT_ACCOUNT_NUMBER = "INPUT_ACCOUNT_NUMBER",
  INPUT_EMAIL = "INPUT_EMAIL",
  INPUT_PASSWORD = "INPUT_PASSWORD",
  INPUT_URL = "INPUT_URL",
  INPUT_AUTOCOMPLETE_API = "INPUT_AUTOCOMPLETE_API",
  INPUT_MULTILINE = "INPUT_MULTILINE",
  SELECT_DROPDOWN = "SELECT_DROPDOWN",
  BOOLEAN = "BOOLEAN",
  DATETIME = "DATETIME",
  SLIDER = "SLIDER",
  SELECT_RADIO = "SELECT_RADIO",
  SWITCH = "SWITCH",
  DATE = "DATE",
  NONE = "NONE",
}

export enum AutoCompleteTrigger {
  DEBOUNCE = "DEBOUNCE",
  THROTTLE = "THROTTLE",
}

export enum Display {
  FORMATTED_VALUE = "FORMATTED_VALUE",
  ROW_VALUE = "ROW_VALUE",
  BOOLEAN = "BOOLEAN",
  DATETIME = "DATETIME",
  NONE = "NONE",
}

export enum Width {
  FULL = "FULL",
  HALF = "HALF",
  NONE = "NONE",
}

export enum MaximumAmountVariableType {
  NONE = "NONE",
  FIXED = "FIXED",
  DYNAMIC = "DYNAMIC",
}

export enum MinimumAmountVariableType {
  NONE = "NONE",
  FIXED = "FIXED",
  DYNAMIC = "DYNAMIC",
}

export enum CreditAccountNumberVariableType {
  NONE = "NONE",
  FIXED = "FIXED",
  DYNAMIC = "DYNAMIC",
}

export enum Platform {
  IOS = "IOS",
  ANDROID = "ANDROID",
  USSD = "USSD",
  WEB = "WEB",
}

export enum UpdatePolicy {
  MANDATORY = "MANDATORY",
  SEMI_MANDATORY = "SEMI_MANDATORY",
  OPTIONAL = "OPTIONAL",
}

export enum AppVersionStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
}

export enum SystemMenuType {
  OTHER_BANK_TRANSFER = "OTHER_BANK_TRANSFER",
  CARDS = "CARDS",
  MERCHANT_MENU = "MERCHANT_MENU",
  TRANSFER = "TRANSFER",
  RECEIVE = "RECEIVE",
  BILL_PAYMENT = "BILL_PAYMENT",
  MOBILE_TOP_UP = "MOBILE_TOP_UP",
  WALLET = "WALLET",
  SETTINGS = "SETTINGS",
  TRANSACTION_HISTORY = "TRANSACTION_HISTORY",
  SUPPORT = "SUPPORT",
  DASHBOARD = "DASHBOARD",
  BENEFICIARY_MANAGEMENT = "BENEFICIARY_MANAGEMENT",
  SCHEDULED_PAYMENT = "SCHEDULED_PAYMENT",
  PAYMENT_REQUEST = "PAYMENT_REQUEST",
  NONE = "NONE",
}

export enum PermissionType {
  SYSTEM = "SYSTEM",
  MONETARY = "MONETARY",
  NON_MONETARY = "NON_MONETARY",
}

export enum ServiceType {
  RETAIL = "RETAIL",
  BUSINESS = "BUSINESS",
}

export enum ServiceDefinitionStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PermissionGroupStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum RoleScope {
  SYSTEM = "SYSTEM",
  CUSTOMER = "CUSTOMER",
}

export enum DeviceType {
  ANDROID = "ANDROID",
  IOS = "IOS",
  WEB = "WEB",
  UNKNOWN = "UNKNOWN",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
  NONE = "NONE",
}

export enum LanguageRelatedStatus {
  VISIBLE = "Visible",
  DISABLE = "Disable",
}
